version: "3.7"
services:
   go:
      image: golang:1.16.3
      volumes:
         - "./:/app"
      working_dir: "/app"
      ports:
         - "9988:8080"
      entrypoint: "go run cmd/http/http.go"
   redis:
      image: redis:5.0.7

